"""
Temporal activity for text chunking.

Three chunking strategies are available and can be selected in the workflow
or via configuration:

  FixedSizeChunker      – Fixed-size chunks with N tokens and O-token overlap.
                          Fast and predictable. Best for uniformly structured content.

  SlidingWindowChunker  – Sliding window with a step smaller than the chunk size.
                          Preserves context across chunk boundaries, improving
                          retrieval quality. (In practice, similar to FixedSize
                          with a larger overlap.)

  SemanticChunker       – TODO: Groups sentences based on cosine similarity.
                          Produces higher-quality chunks but requires embeddings
                          during the chunking phase.

Trade-off:
  A larger overlap generally improves retrieval recall but increases the number
  of chunks, resulting in higher storage and embedding costs.
"""

from __future__ import annotations

import structlog

from retrieval_lab.ingestion.dto import (
    ChunkData,
    ScrapedArticle,
)


log = structlog.getLogger(__name__)


def _split_into_words(text: str) -> list[str]:
    """
    Splits text into words using whitespace.
    This is a lightweight approximation of tokenization.

    Note:
        The actual token count depends on the tokenizer used by the model
        (e.g. `tiktoken` for OpenAI models).

        For this project, treating one word as approximately one token is
        sufficiently accurate.

        If precise token counting is required, install `tiktoken` and use
        `cl100k_base.encode(text)` instead.

    Args:
        text: The input text to split.

    Returns:
        A list of words.
    """
    return text.split()


def _fixed_size_chunk(
    text: str,
    chunk_size: int,
    overlap: int,
) -> list[str]:
    """
    Splits text into chunks of `chunk_size` words with an overlap.

    Example (chunk_size=5, overlap=2):
        "a b c d e f g h" →
            ["a b c d e", "d e f g h"]
             ^^^^^^^       ^^^  (overlap)

    Args:
        text: The input text to split into chunks.
        chunk_size: Maximum number of words in each chunk.
        overlap: Number of overlapping words between consecutive chunks.

    Returns:
        A list of text chunks.
    """
    words = _split_into_words(text)

    if not words:
        return []

    chunks: list[str] = []
    step = chunk_size - overlap
    start = 0

    while start < len(words):
        end = start + chunk_size
        chunk_words = words[start:end]
        chunks.append(" ".join(chunk_words))
        if end >= len(words):
            break
        start += step

    return chunks


def _sliding_window_chunk(
    text: str,
    window_size: int,
    step: int,
) -> list[str]:
    """
    Splits text using a sliding window with an explicit step size.

    More flexible than fixed-size chunking when fine-grained overlap
    control is required.

    Example (window_size=6, step=3):
        "a b c d e f g h i" →
            ["a b c d e f", "d e f g h i", "g h i"]

    Args:
        text: The input text to split into chunks.
        window_size: Number of words in each sliding window.
        step: Number of words to move the window forward after each chunk.

    Returns:
        A list of text chunks.
    """
    words = _split_into_words(text)

    if not words:
        return []

    chunks: list[str] = []
    start = 0

    while start < len(words):
        end = start + window_size
        chunk_words = words[start:end]
        if chunk_words:
            chunks.append(" ".join(chunk_words))
        start += step

    return chunks


def _build_chunk_data(
    raw_chunks: list[str],
    article: ScrapedArticle,
    strategy: str,
) -> list[ChunkData]:
    """
    Wraps raw string chunks into ChunkData objects with metadata.

    Metadata included in every chunk:
      title       – article title (for LLM context and source attribution)
      url         – source URL (displayed to the user in the response)
      source      – source identifier (e.g. "ign", used for filtering)
      chunk_index – chunk position (for debugging and reconstruction)
      strategy    – chunking strategy that was used
      + all metadata from article.meta (tags, genre, platform, etc.)

    Args:
        raw_chunks: List of raw text chunks generated by the chunking strategy.
        article: Scraped article containing content and metadata.
        strategy: Name of the chunking strategy used.

    Returns:
        A list of ChunkData objects containing chunk text and metadata.
    """
    total = len(raw_chunks)
    result: list[ChunkData] = []

    for idx, content in enumerate(raw_chunks):
        meta = {
            "title": article.title,
            "url": article.url,
            "source": article.source,
            "chunk_index": idx,
            "strategy": strategy,
            **article.meta,  # genre, tags, platform iz scrapera
        }

        result.append(
            ChunkData(
                content=content,
                chunk_index=idx,
                total_chunks=total,
                meta=meta,
            )
        )

    return result
